substitutions:
  friendly_name: "Aoycocr X5P"
  project_name: "aoycocr.x5p"
  project_version: "1.0"
  name: aoycocr-x5p
  
esphome:
  name: "${name}"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

dashboard_import:
  package_import_url: github://th0mpy/esphomeconfigs/aoycocr-x5p.yaml


esp8266:
  board: esp01_1m
 
api:

ota:

logger:

web_server:
  port: 80

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime Sensor"

  # https://templates.blakadder.com/aoycocr_X5P.html
  # https://www.esphome-devices.com/devices/Aoycocr-X10S-Plug/

  # Button: GPIO13, Inverted
  # Relay: GPIO15
  # Red LED: GPIO0, Inverted
  # Blue LED: GPIO2, Inverted

  # https://esphome.io/components/binary_sensor/index.html
binary_sensor:
  - platform: gpio
    name: "${friendly_name} Button"
    device_class: power
    pin:
      number: GPIO13
      inverted: true
      # Toggle relay state on button press
    on_press:
      switch.toggle: relay


  # https://esphome.io/components/switch/index.html
switch:
- platform: gpio
  name: "${friendly_name} Relay"
  id: relay
  pin: GPIO15
  # Off on power-on
  restore_mode: ALWAYS_OFF
  # Red LED follows relay state
  on_turn_on:
    then:
    - output.turn_on: red_led
  on_turn_off:
    then:
    - output.turn_off: red_led
- platform: restart
  id: restart_switch
  name: "${friendly_name} Restart"

output:
- platform: gpio
  id: red_led
  pin: 
    number: GPIO0
    inverted: true
  
  # https://esphome.io/components/status_led.html
status_led:
  pin:
    # Blue LED
    number: GPIO2
    inverted: true
