
  # https://templates.blakadder.com/aoycocr_X5P.html
  # https://www.esphome-devices.com/devices/Aoycocr-X10S-Plug/

  # Button: GPIO13, Inverted
  # Relay: GPIO15
  # Red LED: GPIO0, Inverted
  # Blue LED: GPIO2, Inverted

  # https://esphome.io/components/binary_sensor/index.html
binary_sensor:
  - platform: gpio
    name: "${friendly_name} Button"
    device_class: power
    pin:
      number: GPIO13
      inverted: true
      # Toggle relay state on button press
    on_press:
      switch.toggle: relay


  # https://esphome.io/components/switch/index.html
switch:
- platform: gpio
  name: "${friendly_name} Relay"
  id: relay
  pin: GPIO15
  # Off on power-on
  restore_mode: ALWAYS_OFF
  # Red LED follows relay state
  on_turn_on:
    switch.turn_on:
      id: red_led
  on_turn_off:
    switch.turn_off: red_led

- platform: gpio
  name: "${friendly_name} Red Led"
  id: red_led
  pin: 
    number: GPIO0
    inverted: true
    # Off on power-on
  restore_mode: ALWAYS_OFF
  
  # https://esphome.io/components/status_led.html
status_led:
  pin:
    # Blue LED
    number: GPIO2
    inverted: true
