substitutions:
  friendly_name: "Athom RGBWW Light"
  project_name: "athom.rgbww-light"
  project_version: "1.0"
  
esphome:
  name: "${name}"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

dashboard_import:
  package_import_url: github://th0mpy/esphomeconfigs/athom-bulb.yaml


esp8266:
  board: esp8285
 
api:

ota:

logger:

web_server:
  port: 80

wifi:  
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime Sensor"

switch:
  - platform: restart
    id: restart_switch
    name: "${friendly_name} Restart"

output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO14
  - platform: esp8266_pwm
    id: output_warm_white
    pin: GPIO13
  - platform: esp8266_pwm
    id: output_cold_white
    pin: GPIO5
    
light:
  - platform: rgbww
    name: "${friendly_name}"
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cold_white
    warm_white: output_warm_white
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 2700 K
    #restore_mode: ALWAYS_ON
    color_interlock: true
    effects:
      - flicker:
          intensity: 2.5%
          alpha: 98%
      - pulse:
          update_interval: 0.05s
          transition_length: 0.05s
      - strobe:
      - random:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      disabled_by_default: true
      
      
